### ISSUE TITLE
Could you link your .cache/wal/colors.sh?

### ISSUE THREAD

**Issue by E-Duda** [ferb96/dotdotdot#10]

**Comment by ferb96** [comment]
Notice that in my [.xinitrc file](https://github.com/ferb96/dotdotdot/blob/master/xfiles/.xinitrc) there is the command near the end: `wal -f ~/dot/walcolors -a 90`. After running this, wal will generate the file `.cache/wal/colors.sh`. The file `walcolors` is [here](https://github.com/ferb96/dotdotdot/blob/master/walcolors)
